const products = [
    {
      _id: '1',
      name: 'AirPods next level base with Noise cancealing',
      image: '/images/airpods.jpg',
      description: 'Bluetooth wireless earbuds by Apple.',
      brand: 'Apple',
      category: 'Electronics',
      price: 99,
      countInStock: 10,
      rating: 5.5,
      numReviews: 12,
    },
    {
      _id: '2',
      name: 'iPhone 14 Prom max with Optical sensors ',
      image: '/images/alexa.jpg',
      description: 'Apple iPhone 12 with 64GB storage.',
      brand: 'Apple',
      category: 'Electronics',
      price: 799,
      countInStock: 5,
      rating: 4.7,
      numReviews: 18,
    },
    {
      _id: '3',
      name: 'Camera',
      image: '/images/camera.jpg',
      description: 'HD Cameras .',
      brand: 'Samsung',
      category: 'Electronics',
      price: 699,
      countInStock: 7,
      rating: 4.6,
      numReviews: 15,
    },
    {
      _id: '4',
      name: 'Mouse',
      image: '/images/mouse.jpg',
      description: 'High Quality gaming wireless mouse.',
      brand: 'Sony',
      category: 'Electronics',
      price: 299,
      countInStock: 8,
      rating: 2.8,
      numReviews: 22,
    },
    {
      _id: '5',
      name: 'Redmi Phone',
      image: '/images/phone.jpg',
      description: 'State of Art phone for Perfect selfie!.',
      brand: 'Redmi',
      category: 'Electronics',
      price: 299,
      countInStock: 0,
      rating: 3.8,
      numReviews: 22,
    },
    {
      _id: '6',
      name: 'PlayStion x',
      image: '/images/playstation.jpg',
      description: 'The Latest Gaming device on the planet.',
      brand: 'Sony',
      category: 'Electronics',
      price: 240,
      countInStock: 8,
      rating: 1.8,
      numReviews: 22,
    },
    {
      _id: '7',
      name: 'The best Product',
      image: '/images/sample.jpg',
      description: 'Get the best deals ever!.',
      brand: 'Sony',
      category: 'Electronics',
      price: 299,
      countInStock: 8,
      rating: 4.8,
      numReviews: 22,
    },
    {
      _id: '8',
      name: 'TV SETS',
      image: '/images/Apple.jpg',
      description: 'Watch your show in Big screens.',
      brand: 'Sony',
      category: 'Electronics',
      price: 299,
      countInStock: 8,
      rating: 2.8,
      numReviews: 22,
    },
    
  ];
  
  export default products;
  